/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    projects: Project;
    services: Service;
    posts: Post;
    categories: Category;
    leads: Lead;
    subscriptions: Subscription;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Изображения, рендеры, видео. Alt-тексты обязательны для SEO и accessibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Описание изображения для SEO (Image Search) и скринридеров.
   */
  alt: string;
  caption?: string | null;
  /**
   * Фотограф / визуализатор
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    featured?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Динамические страницы сайта (главная, о нас, контакты, услуги).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL: /{slug}
   */
  slug: string;
  /**
   * Перетаскивайте блоки, чтобы собрать страницу. Порядок = порядок на сайте.
   */
  sections?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            image: number | Media;
            ctaPrimary?: {
              label?: string | null;
              href?: string | null;
            };
            ctaSecondary?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-grid';
          }
        | {
            eyebrow?: string | null;
            title: string;
            /**
             * Сколько featured-проектов показать
             */
            limit?: number | null;
            showAllButton?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio-grid';
          }
        | {
            eyebrow?: string | null;
            title: string;
            steps?:
              | {
                  num: string;
                  title: string;
                  description: string;
                  duration?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process-steps';
          }
        | {
            eyebrow?: string | null;
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing-calculator';
          }
        | {
            eyebrow?: string | null;
            title: string;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            layout?: ('narrow' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title: string;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            variant?: ('dark' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-form';
          }
      )[]
    | null;
  /**
   * Метаданные страницы для поисковых систем и социальных сетей.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Кейсы портфолио. Каждая страница кейса — посадочная для SEO long-tail трафика.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL: /portfolio/{slug}
   */
  slug: string;
  /**
   * Краткое описание для карточек и мета-тегов.
   */
  excerpt: string;
  /**
   * Обложка кейса (hero).
   */
  coverImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        type?: ('before' | 'after' | 'render' | 'plan') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Тип проекта, стиль — формирует кластеры и фильтры.
   */
  categories?: (number | Category)[] | null;
  /**
   * Эти данные → структурированный сниппет в выдаче и фильтры на сайте.
   */
  meta?: {
    area?: number | null;
    propertyType?: ('apartment' | 'house' | 'office' | 'hospitality' | 'retail' | 'other') | null;
    style?: ('modern' | 'minimal' | 'scandi' | 'loft' | 'classic' | 'neoclassic' | 'japandi' | 'other') | null;
    location?: string | null;
    year?: number | null;
    duration?: string | null;
    budgetRange?: ('under-500k' | '500k-1m' | '1m-3m' | 'over-3m' | 'private') | null;
  };
  /**
   * Что нужно было решить. Это SEO-контент — пишите подробно.
   */
  brief?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Что сделали и почему именно так.
   */
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
    photo?: (number | null) | Media;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Показывать на главной в «Избранных проектах».
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Категории проектов и услуг: квартира, офис, визуализация и т.д. — основа для SEO-кластеров.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  /**
   * Для SEO — выводится на странице категории.
   */
  description?: string | null;
  type: 'project' | 'service' | 'style';
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Каждая услуга = отдельная посадочная страница под SEO/рекламу.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL: /services/{slug}
   */
  slug: string;
  /**
   * Иконка/мини-рендер для карточки услуги.
   */
  icon?: (number | null) | Media;
  /**
   * 1 предложение для карточки в сетке услуг.
   */
  shortDescription: string;
  /**
   * H1 посадочной страницы услуги.
   */
  heroHeadline: string;
  heroSubheadline?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Что беспокоит клиента → снимаем возражения.
   */
  painPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        item: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pricing?: {
    priceFrom?: number | null;
    unit?: ('sqm' | 'project' | 'hour' | 'render') | null;
    note?: string | null;
  };
  /**
   * Вопросы → микроразметка FAQPage = расширенный сниппет в Google.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Кейсы по этой услуге.
   */
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Сортировка на странице услуг.
   */
  order?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Статьи и гайды — SEO-движок сайта. Каждая статья под 1 ключевое слово.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL: /blog/{slug}
   */
  slug: string;
  /**
   * Анонс для списка статей и meta description.
   */
  excerpt: string;
  coverImage: number | Media;
  category?: (number | null) | Category;
  tags?: (number | Category)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  /**
   * Дата публикации. Статья скрыта до этой даты.
   */
  publishedAt?: string | null;
  /**
   * В минутах (можно оставить пустым — посчитается автоматически).
   */
  readingTime?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  relatedPosts?: (number | Post)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Заявки с сайта. Сортируйте по status и source для воронки продаж.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  /**
   * Минимум одно поле контакта (email или телефон).
   */
  contact: {
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Интересующая услуга — определяет квалификацию лида.
   */
  service?: (number | null) | Service;
  projectDetails?: {
    propertyType?: string | null;
    area?: number | null;
    budget?: string | null;
    timeline?: string | null;
  };
  message: string;
  source?:
    | (
        | 'website'
        | 'calculator'
        | 'lead-magnet'
        | 'whatsapp'
        | 'telegram'
        | 'ads-google'
        | 'ads-yandex'
        | 'social'
        | 'referral'
        | 'other'
      )
    | null;
  status?: ('new' | 'in-progress' | 'qualified' | 'meeting' | 'won' | 'lost' | 'nurture') | null;
  assignedTo?: (number | null) | User;
  notes?: string | null;
  /**
   * Согласие на обработку персональных данных.
   */
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email-подписчики (лид-магниты, рассылка). Не путать с заявками — это контакты для прогрева.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  email: string;
  name?: string | null;
  source?: ('lead-magnet' | 'newsletter' | 'popup' | 'footer' | 'blog') | null;
  /**
   * Какой лид-магнит скачали (slug)
   */
  leadMagnet?: string | null;
  status?: ('subscribed' | 'pending' | 'unsubscribed' | 'nurturing') | null;
  consent: boolean;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        featured?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              image?: T;
              ctaPrimary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              ctaSecondary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-grid'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'portfolio-grid'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              limit?: T;
              showAllButton?: T;
              id?: T;
              blockName?: T;
            };
        'process-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              steps?:
                | T
                | {
                    num?: T;
                    title?: T;
                    description?: T;
                    duration?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pricing-calculator'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              title?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        'contact-form'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        type?: T;
        id?: T;
      };
  categories?: T;
  meta?:
    | T
    | {
        area?: T;
        propertyType?: T;
        style?: T;
        location?: T;
        year?: T;
        duration?: T;
        budgetRange?: T;
      };
  brief?: T;
  solution?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        photo?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroImage?: T;
  painPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        item?: T;
        description?: T;
        id?: T;
      };
  body?: T;
  pricing?:
    | T
    | {
        priceFrom?: T;
        unit?: T;
        note?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedProjects?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  tags?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  service?: T;
  projectDetails?:
    | T
    | {
        propertyType?: T;
        area?: T;
        budget?: T;
        timeline?: T;
      };
  message?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  notes?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  source?: T;
  leadMagnet?: T;
  status?: T;
  consent?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Глобальные настройки сайта: контакты, SEO по умолчанию, интеграции.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  brand?: {
    name?: string | null;
    tagline?: string | null;
    logo?: (number | null) | Media;
    logoDark?: (number | null) | Media;
  };
  contacts?: {
    email?: string | null;
    phone?: string | null;
    /**
     * С кодом страны, напр. 79991234567
     */
    whatsapp?: string | null;
    /**
     * Username без @
     */
    telegram?: string | null;
    instagram?: string | null;
    address?: string | null;
    /**
     * URL embed Google/Яндекс Карт
     */
    mapEmbed?: string | null;
  };
  socialProof?: {
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    pressLogos?:
      | {
          name?: string | null;
          logo?: (number | null) | Media;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seoDefaults?: {
    title?: string | null;
    /**
     * Шаблон: %s — разделитель
     */
    descriptionTemplate?: string | null;
    defaultOgImage?: (number | null) | Media;
    googleVerification?: string | null;
    yandexVerification?: string | null;
  };
  analytics?: {
    gaId?: string | null;
    yandexMetrikaId?: string | null;
    plausibleDomain?: string | null;
  };
  leadMagnet?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    guideFile?: (number | null) | Media;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
        logo?: T;
        logoDark?: T;
      };
  contacts?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        telegram?: T;
        instagram?: T;
        address?: T;
        mapEmbed?: T;
      };
  socialProof?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        pressLogos?:
          | T
          | {
              name?: T;
              logo?: T;
              url?: T;
              id?: T;
            };
      };
  seoDefaults?:
    | T
    | {
        title?: T;
        descriptionTemplate?: T;
        defaultOgImage?: T;
        googleVerification?: T;
        yandexVerification?: T;
      };
  analytics?:
    | T
    | {
        gaId?: T;
        yandexMetrikaId?: T;
        plausibleDomain?: T;
      };
  leadMagnet?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        guideFile?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}